language: php
sudo: false
php:
  - 7.2
  - 7.3
  - 7.4
env:
  - SYMFONY_VERSION=~5.0

before_install:
  - composer require --no-update symfony/console $SYMFONY_VERSION
  - composer require --no-update symfony/dependency-injection $SYMFONY_VERSION
  - composer require --no-update symfony/config $SYMFONY_VERSION
  - composer require --no-update symfony/yaml $SYMFONY_VERSION
  - composer require --no-update symfony/finder $SYMFONY_VERSION
  - composer require --no-update symfony/filesystem $SYMFONY_VERSION
  - composer require --no-update symfony/event-dispatcher $SYMFONY_VERSION

install:
  - composer install --prefer-dist

script:
  - ./typoscript-lint --help
  - vendor/bin/phpunit --coverage-clover clover.xml
  - vendor/bin/psalm
