services:
  tokenize_command:
    class: Helmich\TypoScriptLint\Command\TokenizeCommand
    calls:
      - [injectTokenizer, [@tokenizer]]
      - [injectTokenPrinter, [@token_printer_structured]]
  lint_command:
    class: Helmich\TypoScriptLint\Command\LintCommand
    calls:
      - [injectLinter, [@linter]]
      - [injectLinterConfigurationLocator, [@linter_configuration_locator]]
      - [injectReportPrinterLocator, [@printer_locator]]
  parse_command:
    class: Helmich\TypoScriptLint\Command\ParseCommand
    calls:
      - [injectParser, [@parser]]
  linter:
    class: Helmich\TypoScriptLint\Linter\Linter
    arguments: [@tokenizer, @parser, @sniff_locator]
  linter_configuration:
    class: Helmich\TypoScriptLint\Linter\LinterConfiguration
  linter_configuration_locator:
    class: Helmich\TypoScriptLint\Linter\Configuration\ConfigurationLocator
  printer_locator:
    class: Helmich\TypoScriptLint\Linter\ReportPrinter\PrinterLocator
  sniff_locator:
    class: Helmich\TypoScriptLint\Linter\Sniff\SniffLocator