services:
  tokenize_command:
    class: Helmich\TsParser\Command\TokenizeCommand
    calls:
      - [injectTokenizer, ["@tokenizer"]]
      - [injectTokenPrinter, ["@token_printer_code"]]
  lint_command:
    class: Helmich\TsParser\Command\LintCommand
    calls:
      - [injectLinter, [@linter]]
      - [injectLinterConfigurationLocator, [@linter_configuration_locator]]
  tokenizer:
    class: Helmich\TsParser\Tokenizer\Tokenizer
  token_printer_structured:
    class: Helmich\TsParser\Tokenizer\Printer\StructuredTokenPrinter
  token_printer_code:
    class: Helmich\TsParser\Tokenizer\Printer\CodeTokenPrinter
  linter:
    class: Helmich\TsParser\Linter\Linter
    arguments: [@tokenizer, @sniff_locator]
  linter_configuration:
    class: Helmich\TsParser\Linter\LinterConfiguration
  linter_configuration_locator:
    class: Helmich\TsParser\Linter\Configuration\ConfigurationLocator
  sniff_locator:
    class: Helmich\TsParser\Linter\Sniff\SniffLocator
#      - [setNamespaceConverter, ["@namespace_converter_astbased"]]
#  file_locator:
#    class: Helmich\Namespacify\File\FileLocator
#  namespace_converter_astbased:
#    class: Helmich\Namespacify\Converter\ASTBasedNamespaceConverter
#    arguments: ["@php_parser"]
#  namespace_converter_forward:
#    class: Helmich\Namespacify\Converter\ForwardNamespaceConverter
#  namespace_converter_backward:
#    class: Helmich\Namespacify\Converter\BackwardNamespaceConverter
#    arguments: ["@php_parser"]
#  php_parser:
#    class: 'PhpParser\Parser'
#    arguments: ["@php_lexer"]
#  php_lexer:
#    class: 'PhpParser\Lexer'