services:
  tokenize_command:
    class: Helmich\TsParser\Command\TokenizeCommand
    calls:
      - [injectTokenizer, ["@tokenizer"]]
      - [injectTokenPrinter, ["@token_printer_structured"]]
  lint_command:
    class: Helmich\TsParser\Command\LintCommand
    calls:
      - [injectLinter, [@linter]]
      - [injectLinterConfigurationLocator, [@linter_configuration_locator]]
      - [injectReportPrinterLocator, [@printer_locator]]
  parse_command:
    class: Helmich\TsParser\Command\ParseCommand
    calls:
      - [injectParser, [@parser]]
  tokenizer:
    class: Helmich\TsParser\Tokenizer\Tokenizer
  token_printer_structured:
    class: Helmich\TsParser\Tokenizer\Printer\StructuredTokenPrinter
  token_printer_code:
    class: Helmich\TsParser\Tokenizer\Printer\CodeTokenPrinter
  linter:
    class: Helmich\TsParser\Linter\Linter
    arguments: [@tokenizer, @parser, @sniff_locator]
  linter_configuration:
    class: Helmich\TsParser\Linter\LinterConfiguration
  linter_configuration_locator:
    class: Helmich\TsParser\Linter\Configuration\ConfigurationLocator
  printer_locator:
    class: Helmich\TsParser\Linter\ReportPrinter\PrinterLocator
  sniff_locator:
    class: Helmich\TsParser\Linter\Sniff\SniffLocator
  parser:
    class: Helmich\TsParser\Parser\Parser
    arguments: [@tokenizer]